# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.cache/wt [current_project]
set_property parent.project_path C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/16numadder/16numadder.srcs/sources_1/new/16_num_adder.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/3bitdecoder.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/41mux.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/CU.vhd
  {C:/Users/Bogda/Desktop/facky/Sem2/DSD/Vivado Projects/lab7DFFtb/lab7DFFtb.srcs/sources_1/new/DFF.vhd}
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/EU.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/16numadder/16numadder.srcs/sources_1/new/adder_12_bit.vhd
  {C:/Users/Bogda/Desktop/facky/Sem2/DSD/Vivado Projects/lab4freqdiv/lab4freqdiv.srcs/sources_1/new/clk1hz.vhd}
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/clk25.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/ssd_dec/ssd_dec.srcs/sources_1/new/clk_div17.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/data_buffer/data_buffer.srcs/sources_1/new/data_buff.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/data_gen.vhd
  {C:/Users/Bogda/Desktop/facky/Sem2/DSD/Vivado Projects/lab4debouncer/lab4debouncer.srcs/sources_1/new/debouncer.vhd}
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/16numadder/16numadder.srcs/sources_1/new/full_adder_1bit.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/hold_reg.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/mux41_2.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/prbs4.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/prbs8.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/data_buffer/data_buffer.srcs/sources_1/new/registers.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/shift_count.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/shift_reg.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/ssd_dec/ssd_dec.srcs/sources_1/new/ssd.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/stud1.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/stud2.vhd
  C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/mainproj/mainproj.srcs/sources_1/new/main.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/basys_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Bogda/Desktop/facky/Sem2/DSD/Project/IMPLEMENTATION/basys_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
